services:
  db:
    image: postgres:15-alpine
    container_name: zhest-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: zhest
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./postgre.sql:/docker-entrypoint-initdb.d/init.sql
